import './globals.css';
import '../libs/fontawesome/css/all.min.css'
import Navbar from '@/components/navbar';

export const metadata = {
  title: 'Pizza',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body >
        <Navbar/>
          {children}
      </body>
    </html>
  )
}
